server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;
  # /login -> login.html, /register -> register.html, else index.html
  location / { try_files $uri $uri.html $uri/ /index.html; }
}
